stages:
  prepare:
    cmd: python src/preprocessing.py
    deps:
      - data/world_happiness_report.csv
      - src/preprocessing.py
    outs:
      - data/processed_X_train_data.csv
      - data/processed_y_train_data.csv
      - data/processed_X_val_data.csv
      - data/processed_y_val_data.csv
      - data/processed_X_test_data.csv
      - data/processed_y_test_data.csv